# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-18 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementSystem', '0002_remove_slkf_membername'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SL', 'SLKF'), ('AS', 'association'), ('DI', 'district'), ('PR', 'province'), ('AD', 'admin')], default='AD', max_length=2),
        ),
    ]
