# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-18 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementSystem', '0004_auto_20180918_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='telephone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='slkf',
            name='telephone',
            field=models.CharField(max_length=12),
        ),
    ]
