# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementSystem', '0006_auto_20180930_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
            ],
        ),
    ]
