# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-02 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementSystem', '0009_association_associationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='associationID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
