# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-03 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementSystem', '0010_auto_20181002_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerName', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='chiefInstructorName',
            field=models.CharField(default='A.S. Silva', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManagementSystem.Association'),
        ),
        migrations.AddField(
            model_name='player',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManagementSystem.District'),
        ),
        migrations.AddField(
            model_name='player',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManagementSystem.Event'),
        ),
    ]
