# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-05 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementSystem', '0012_auto_20181005_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='associationID',
        ),
    ]
