# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-10 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementSystem', '0013_remove_association_associationid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coachID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coachName', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=12)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManagementSystem.Association')),
            ],
        ),
    ]
