# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-21 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementSystem', '0014_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateID', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('isOpen', models.BooleanField(default=True, help_text='Designates whether the registration is open.', verbose_name='active')),
            ],
        ),
    ]
