# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-08 14:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventManagementSystem', '0015_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kumite',
            field=models.BooleanField(default=True, help_text='Kumite event or not', verbose_name='Event Category'),
        ),
        migrations.AlterField(
            model_name='association',
            name='associationName',
            field=models.CharField(max_length=100, verbose_name='Association Name'),
        ),
        migrations.AlterField(
            model_name='association',
            name='chiefInstructorName',
            field=models.CharField(max_length=100, verbose_name='Chief Instructor Name'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManagementSystem.Association', verbose_name='Association Name'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coachID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='coachName',
            field=models.CharField(max_length=100, verbose_name='Name of the Coach'),
        ),
        migrations.AlterField(
            model_name='district',
            name='districtSecretaryName',
            field=models.CharField(max_length=100, verbose_name='District Secretary Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventID',
            field=models.SmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Event Number'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventName',
            field=models.CharField(max_length=100, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventManagementSystem.Association', verbose_name='Association Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='playerName',
            field=models.CharField(max_length=100, verbose_name='Player Name'),
        ),
        migrations.AlterField(
            model_name='player',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='province',
            name='provinceSecretaryName',
            field=models.CharField(max_length=100, verbose_name='Province Secretary Name'),
        ),
        migrations.AlterField(
            model_name='slkf',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Position at SLKF'),
        ),
    ]
